### ISSUE TITLE
Installing athena in linux

### ISSUE THREAD

**Issue by bambang-ap** [athena-oss/athena#20]
How can i install athena in linux ubuntu?

**Comment by rafaelspinto** [comment]
Hi @aprakoso98, we are working on building the debian packages to be easier but in the meantime you can just clone the repo:

``` bash
git clone https://github.com/athena-oss/athena.git
```

after this you can install the existing plugins or create your own, example :

``` bash
# cd into athena folder
cd athena

# install the php plugin
./athena plugins install php  https://github.com/athena-oss/plugin-php

# create your own plugin
./athena wizard start
```

please let me know if this works out for you.

**Comment by aprakoso98** [comment]
thanks for answering me @rafaelspinto 
and i have new problem 
![Uploading Screenshot from 2016-10-03 16-06-55.png…]()

**Comment by bambang-ap** [comment]
thanks for answering me @rafaelspinto 
and here i found https://cloud.githubusercontent.com/assets/18139422/19032459/06db2a58-8984-11e6-9c64-42507417567b.png

**Comment by bambang-ap** [comment]
sory my mistake :D 
the issue solved :+1:
