### ISSUE TITLE
athena fails if directory name has space

### ISSUE THREAD

**Issue by abhishektomar-olx** [athena-oss/athena#32]
I am using Google Drive for storing my data in cloud and my directory structure is something like **"/Users/abhishektomar/Google Drive/infra/athena"** but whenever I am running **athena** command to do any thing it failed because of space in a directory name.

error what  I am getting is:
`docker: Error parsing reference: "Drive/infra/athena/terraform:/opt/platform_terraform" is not a valid repository/tag.`

**Comment by pproenca** [comment]
Hello @abhishektomar-olx 

We've found a few places where directories with spaces were not being parsed correctly:
- https://github.com/athena-oss/athena/commit/96062ef77963b6c4eb62e2ee50c01fc3a2422680
- https://github.com/athena-oss/athena/commit/4a1347b0128d142192555f1a4bbec68d7884d138

These are now fixed.

However make sure also that in the plugin you are using, which seems to be a custom one, that all directories paths in the docker mount functions are wrapped around double quotes.

**Comment by ghost** [comment]
I'm closing it as we have a test case for this now. @abhishektomar-olx if you continue to experience this issue please reopen it.
