### ISSUE TITLE
Basic authentication support

### ISSUE THREAD

**Issue by yael-lorenzo** [athena-oss/athena#35]
It could be great to have basic authentication support and set the parameters in the athena.json file.

**Comment by pproenca** [comment]
Hey @yael-lorenzo-olx 

Could you please elaborate more? Could you provide some examples or use cases?

**Comment by yael-lorenzo** [comment]
After using it, it is a bit hard to think of multi purpose model to do it. Perhaps this is for documentation and just as an informative case.

We are using the FluentRequestInterface to create the WEB requests and it has a function withBasicAuth($username, $password);

We are loading from athena.json file the user and pwd to set this up.
